package com.smart.home.modules.other.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RptDashboardExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    public RptDashboardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rpt_dashboard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public RptDashboardExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rpt_dashboard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public RptDashboardExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    public void setPageInfo(Integer currentPage, Integer pageSize) {
        if(pageSize<1) throw new IllegalArgumentException("页大小不能小于1！");
        this.limit=pageSize;
        if(currentPage<1) throw new IllegalArgumentException("页数不能小于1！");
        this.offset=(currentPage-1)*pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rpt_dashboard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        RptDashboardExample example = new RptDashboardExample();
        return example.createCriteria();
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterionForJDBCDate("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreatedTimeEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("created_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreatedTimeNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("created_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreatedTimeGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("created_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreatedTimeGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("created_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterionForJDBCDate("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreatedTimeLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("created_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreatedTimeLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("created_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterionForJDBCDate("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLiveCountIsNull() {
            addCriterion("live_count is null");
            return (Criteria) this;
        }

        public Criteria andLiveCountIsNotNull() {
            addCriterion("live_count is not null");
            return (Criteria) this;
        }

        public Criteria andLiveCountEqualTo(Integer value) {
            addCriterion("live_count =", value, "liveCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLiveCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("live_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLiveCountNotEqualTo(Integer value) {
            addCriterion("live_count <>", value, "liveCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLiveCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("live_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLiveCountGreaterThan(Integer value) {
            addCriterion("live_count >", value, "liveCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLiveCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("live_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLiveCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("live_count >=", value, "liveCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLiveCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("live_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLiveCountLessThan(Integer value) {
            addCriterion("live_count <", value, "liveCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLiveCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("live_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLiveCountLessThanOrEqualTo(Integer value) {
            addCriterion("live_count <=", value, "liveCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLiveCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("live_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLiveCountIn(List<Integer> values) {
            addCriterion("live_count in", values, "liveCount");
            return (Criteria) this;
        }

        public Criteria andLiveCountNotIn(List<Integer> values) {
            addCriterion("live_count not in", values, "liveCount");
            return (Criteria) this;
        }

        public Criteria andLiveCountBetween(Integer value1, Integer value2) {
            addCriterion("live_count between", value1, value2, "liveCount");
            return (Criteria) this;
        }

        public Criteria andLiveCountNotBetween(Integer value1, Integer value2) {
            addCriterion("live_count not between", value1, value2, "liveCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountIsNull() {
            addCriterion("article_count is null");
            return (Criteria) this;
        }

        public Criteria andArticleCountIsNotNull() {
            addCriterion("article_count is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCountEqualTo(Long value) {
            addCriterion("article_count =", value, "articleCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCountNotEqualTo(Long value) {
            addCriterion("article_count <>", value, "articleCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCountGreaterThan(Long value) {
            addCriterion("article_count >", value, "articleCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCountGreaterThanOrEqualTo(Long value) {
            addCriterion("article_count >=", value, "articleCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCountLessThan(Long value) {
            addCriterion("article_count <", value, "articleCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCountLessThanOrEqualTo(Long value) {
            addCriterion("article_count <=", value, "articleCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCountIn(List<Long> values) {
            addCriterion("article_count in", values, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountNotIn(List<Long> values) {
            addCriterion("article_count not in", values, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountBetween(Long value1, Long value2) {
            addCriterion("article_count between", value1, value2, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountNotBetween(Long value1, Long value2) {
            addCriterion("article_count not between", value1, value2, "articleCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountIsNull() {
            addCriterion("video_count is null");
            return (Criteria) this;
        }

        public Criteria andVideoCountIsNotNull() {
            addCriterion("video_count is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCountEqualTo(Long value) {
            addCriterion("video_count =", value, "videoCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCountNotEqualTo(Long value) {
            addCriterion("video_count <>", value, "videoCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCountGreaterThan(Long value) {
            addCriterion("video_count >", value, "videoCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCountGreaterThanOrEqualTo(Long value) {
            addCriterion("video_count >=", value, "videoCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCountLessThan(Long value) {
            addCriterion("video_count <", value, "videoCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCountLessThanOrEqualTo(Long value) {
            addCriterion("video_count <=", value, "videoCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCountIn(List<Long> values) {
            addCriterion("video_count in", values, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountNotIn(List<Long> values) {
            addCriterion("video_count not in", values, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountBetween(Long value1, Long value2) {
            addCriterion("video_count between", value1, value2, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountNotBetween(Long value1, Long value2) {
            addCriterion("video_count not between", value1, value2, "videoCount");
            return (Criteria) this;
        }

        public Criteria andPostCountIsNull() {
            addCriterion("post_count is null");
            return (Criteria) this;
        }

        public Criteria andPostCountIsNotNull() {
            addCriterion("post_count is not null");
            return (Criteria) this;
        }

        public Criteria andPostCountEqualTo(Long value) {
            addCriterion("post_count =", value, "postCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostCountNotEqualTo(Long value) {
            addCriterion("post_count <>", value, "postCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostCountGreaterThan(Long value) {
            addCriterion("post_count >", value, "postCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostCountGreaterThanOrEqualTo(Long value) {
            addCriterion("post_count >=", value, "postCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostCountLessThan(Long value) {
            addCriterion("post_count <", value, "postCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostCountLessThanOrEqualTo(Long value) {
            addCriterion("post_count <=", value, "postCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostCountIn(List<Long> values) {
            addCriterion("post_count in", values, "postCount");
            return (Criteria) this;
        }

        public Criteria andPostCountNotIn(List<Long> values) {
            addCriterion("post_count not in", values, "postCount");
            return (Criteria) this;
        }

        public Criteria andPostCountBetween(Long value1, Long value2) {
            addCriterion("post_count between", value1, value2, "postCount");
            return (Criteria) this;
        }

        public Criteria andPostCountNotBetween(Long value1, Long value2) {
            addCriterion("post_count not between", value1, value2, "postCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentCountIsNull() {
            addCriterion("product_comment_count is null");
            return (Criteria) this;
        }

        public Criteria andProductCommentCountIsNotNull() {
            addCriterion("product_comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andProductCommentCountEqualTo(Long value) {
            addCriterion("product_comment_count =", value, "productCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentCountNotEqualTo(Long value) {
            addCriterion("product_comment_count <>", value, "productCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentCountGreaterThan(Long value) {
            addCriterion("product_comment_count >", value, "productCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentCountGreaterThanOrEqualTo(Long value) {
            addCriterion("product_comment_count >=", value, "productCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentCountLessThan(Long value) {
            addCriterion("product_comment_count <", value, "productCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentCountLessThanOrEqualTo(Long value) {
            addCriterion("product_comment_count <=", value, "productCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentCountIn(List<Long> values) {
            addCriterion("product_comment_count in", values, "productCommentCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentCountNotIn(List<Long> values) {
            addCriterion("product_comment_count not in", values, "productCommentCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentCountBetween(Long value1, Long value2) {
            addCriterion("product_comment_count between", value1, value2, "productCommentCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentCountNotBetween(Long value1, Long value2) {
            addCriterion("product_comment_count not between", value1, value2, "productCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIsNull() {
            addCriterion("article_comment_count is null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIsNotNull() {
            addCriterion("article_comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountEqualTo(Long value) {
            addCriterion("article_comment_count =", value, "articleCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCommentCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_comment_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotEqualTo(Long value) {
            addCriterion("article_comment_count <>", value, "articleCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCommentCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_comment_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountGreaterThan(Long value) {
            addCriterion("article_comment_count >", value, "articleCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCommentCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_comment_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountGreaterThanOrEqualTo(Long value) {
            addCriterion("article_comment_count >=", value, "articleCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCommentCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_comment_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountLessThan(Long value) {
            addCriterion("article_comment_count <", value, "articleCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCommentCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_comment_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountLessThanOrEqualTo(Long value) {
            addCriterion("article_comment_count <=", value, "articleCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andArticleCommentCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("article_comment_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIn(List<Long> values) {
            addCriterion("article_comment_count in", values, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotIn(List<Long> values) {
            addCriterion("article_comment_count not in", values, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountBetween(Long value1, Long value2) {
            addCriterion("article_comment_count between", value1, value2, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotBetween(Long value1, Long value2) {
            addCriterion("article_comment_count not between", value1, value2, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountIsNull() {
            addCriterion("video_comment_count is null");
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountIsNotNull() {
            addCriterion("video_comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountEqualTo(Long value) {
            addCriterion("video_comment_count =", value, "videoCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCommentCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_comment_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountNotEqualTo(Long value) {
            addCriterion("video_comment_count <>", value, "videoCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCommentCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_comment_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountGreaterThan(Long value) {
            addCriterion("video_comment_count >", value, "videoCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCommentCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_comment_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountGreaterThanOrEqualTo(Long value) {
            addCriterion("video_comment_count >=", value, "videoCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCommentCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_comment_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountLessThan(Long value) {
            addCriterion("video_comment_count <", value, "videoCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCommentCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_comment_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountLessThanOrEqualTo(Long value) {
            addCriterion("video_comment_count <=", value, "videoCommentCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVideoCommentCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("video_comment_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountIn(List<Long> values) {
            addCriterion("video_comment_count in", values, "videoCommentCount");
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountNotIn(List<Long> values) {
            addCriterion("video_comment_count not in", values, "videoCommentCount");
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountBetween(Long value1, Long value2) {
            addCriterion("video_comment_count between", value1, value2, "videoCommentCount");
            return (Criteria) this;
        }

        public Criteria andVideoCommentCountNotBetween(Long value1, Long value2) {
            addCriterion("video_comment_count not between", value1, value2, "videoCommentCount");
            return (Criteria) this;
        }

        public Criteria andPostReplyCountIsNull() {
            addCriterion("post_reply_count is null");
            return (Criteria) this;
        }

        public Criteria andPostReplyCountIsNotNull() {
            addCriterion("post_reply_count is not null");
            return (Criteria) this;
        }

        public Criteria andPostReplyCountEqualTo(Long value) {
            addCriterion("post_reply_count =", value, "postReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostReplyCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_reply_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostReplyCountNotEqualTo(Long value) {
            addCriterion("post_reply_count <>", value, "postReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostReplyCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_reply_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostReplyCountGreaterThan(Long value) {
            addCriterion("post_reply_count >", value, "postReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostReplyCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_reply_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostReplyCountGreaterThanOrEqualTo(Long value) {
            addCriterion("post_reply_count >=", value, "postReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostReplyCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_reply_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostReplyCountLessThan(Long value) {
            addCriterion("post_reply_count <", value, "postReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostReplyCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_reply_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostReplyCountLessThanOrEqualTo(Long value) {
            addCriterion("post_reply_count <=", value, "postReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andPostReplyCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("post_reply_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPostReplyCountIn(List<Long> values) {
            addCriterion("post_reply_count in", values, "postReplyCount");
            return (Criteria) this;
        }

        public Criteria andPostReplyCountNotIn(List<Long> values) {
            addCriterion("post_reply_count not in", values, "postReplyCount");
            return (Criteria) this;
        }

        public Criteria andPostReplyCountBetween(Long value1, Long value2) {
            addCriterion("post_reply_count between", value1, value2, "postReplyCount");
            return (Criteria) this;
        }

        public Criteria andPostReplyCountNotBetween(Long value1, Long value2) {
            addCriterion("post_reply_count not between", value1, value2, "postReplyCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountIsNull() {
            addCriterion("product_comment_reply_count is null");
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountIsNotNull() {
            addCriterion("product_comment_reply_count is not null");
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountEqualTo(Long value) {
            addCriterion("product_comment_reply_count =", value, "productCommentReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentReplyCountEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_reply_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountNotEqualTo(Long value) {
            addCriterion("product_comment_reply_count <>", value, "productCommentReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentReplyCountNotEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_reply_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountGreaterThan(Long value) {
            addCriterion("product_comment_reply_count >", value, "productCommentReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentReplyCountGreaterThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_reply_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountGreaterThanOrEqualTo(Long value) {
            addCriterion("product_comment_reply_count >=", value, "productCommentReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentReplyCountGreaterThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_reply_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountLessThan(Long value) {
            addCriterion("product_comment_reply_count <", value, "productCommentReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentReplyCountLessThanColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_reply_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountLessThanOrEqualTo(Long value) {
            addCriterion("product_comment_reply_count <=", value, "productCommentReplyCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProductCommentReplyCountLessThanOrEqualToColumn(RptDashboard.Column column) {
            addCriterion(new StringBuilder("product_comment_reply_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountIn(List<Long> values) {
            addCriterion("product_comment_reply_count in", values, "productCommentReplyCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountNotIn(List<Long> values) {
            addCriterion("product_comment_reply_count not in", values, "productCommentReplyCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountBetween(Long value1, Long value2) {
            addCriterion("product_comment_reply_count between", value1, value2, "productCommentReplyCount");
            return (Criteria) this;
        }

        public Criteria andProductCommentReplyCountNotBetween(Long value1, Long value2) {
            addCriterion("product_comment_reply_count not between", value1, value2, "productCommentReplyCount");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private RptDashboardExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(RptDashboardExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public RptDashboardExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table public.rpt_dashboard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table public.rpt_dashboard
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}